### ISSUE TITLE
Cant Use Routing with CupertinoTabScaffold

### ISSUE THREAD

**Issue by keremalan** [keremalan/lugat-app#3]
Hi, [this](https://github.com/keremalan/lugat-app/blob/main/draft_6/main.dart) / or use this: https://github.com/keremalan/lugat-app/blob/main/draft_6/main.dart draft_6, main.dart have issue. I want to use GestureCapture and route to my TechCategory page, but this app don't accept any routing ways.

**Comment by keremalan** [comment]
Try to use this routing format: https://github.com/keremalan/dart-readyToUse/blob/main/routeAndCategories/main.dart

**Comment by keremalan** [comment]
This is file get issue when I use routing: https://github.com/keremalan/lugat-app/blob/main/issue_draft_6/main.dart

**Comment by keremalan** [comment]
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
Could not find a generator for route RouteSettings("/technology", null) in the _CupertinoTabViewState.

Generators for routes are searched for in the following order:
 1. For the "/" route, the "builder" property, if non-null, is used.
 2. Otherwise, the "routes" table is used, if it has an entry for the route.
 3. Otherwise, onGenerateRoute is called. It should return a non-null value for any valid route not handled by "builder" and "routes".
 4. Finally if all else fails onUnknownRoute is called.
Unfortunately, onUnknownRoute was not set.
When the exception was thrown, this was the stack: 
#0      _CupertinoTabViewState._onUnknownRoute.<anonymous closure> (package:flutter/src/cupertino/tab_view.dart:202:9)
#1      _CupertinoTabViewState._onUnknownRoute (package:flutter/src/cupertino/tab_view.dart:215:6)
#2      NavigatorState._routeNamed (package:flutter/src/widgets/navigator.dart:4013:37)
#3      NavigatorState.pushNamed (package:flutter/src/widgets/navigator.dart:4055:20)
#4      Navigator.pushNamed (package:flutter/src/widgets/navigator.dart:1621:34)
#5      HomeTab.build.<anonymous closure> (package:scroll/main.dart:79:23)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
#10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9)
#11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
#19     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#20     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#26     _invoke1 (dart:ui/hooks.dart:169:10)
#27     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#28     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)
(elided 3 frames from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#ae7d9
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(190.7, 469.0)
  finalLocalPosition: Offset(24.2, 18.0)
  button: 1
  sent tap down
====================================================================================================

**Comment by keremalan** [comment]
Fixed with: https://github.com/keremalan/lugat-app/blob/main/draft_7/main.dart
